spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug